endpoints:
    - chain-id: LAV1
      api-interface: rest
      network-address: 127.0.0.1:3360
    - chain-id: LAV1
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3361
    - chain-id: LAV1
      api-interface: grpc
      network-address: 127.0.0.1:3362