name: Lava E2E Tests

on: [pull_request]

jobs:
  test-protocol-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.5

    # Setup Paths
    - name: home
      run:  pwd && ls -l
    - name: ls usr 
      run: ls -l /home/runner/work/lava/lava
    - name: cp lava
      run:  cp -r ~/work/lava/lava ~/go/lava 
    - name: export PATH
      run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
    # - name: export
    #   run: export PATH=$PATH:/go/lava
    - name: export GOPATH
      run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
    - name: export LAVA
      run: export LAVA=/home/runner/work/lava/lava
    - name: go env
      run:  go env
    - name: pwd
      run: pwd
    - name: tree
      run: tree
    - name: ls -l
      run: ls -l

    ######################################################
    ### Run Lava E2E Tests 
    ######################################################
    - name: Run Lava E2E Tests -timeout 1200s
      run: go test ./testutil/e2e/ -run ^TestLavaProtocol$ -v -timeout 1200s # 20mins
      
    - name: tail -n 300 Lavad Logs
      if: always()
      run: tail -n 300 testutil/e2e/protocolLogs/00_StartLava.log

    - name: Stake Lava All Logs
      if: always()
      run: cat testutil/e2e/protocolLogs/01_stakeLava.log

    - name: Stake Lava Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/protocolLogs/01_stakeLava_errors.log

    - name: head -n 300 JSON Proxy Logs
      if: always()
      run: head -n 300 testutil/e2e/protocolLogs/02_jsonProxy.log

    - name: tail -n 300 JSON Proxy Logs
      if: always()
      run: tail -n 300 testutil/e2e/protocolLogs/02_jsonProxy.log

    - name: JSON Proxy Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/protocolLogs/02_jsonProxy_errors.log

    - name: JSON Provider All Logs
      if: always()
      run: grep "" testutil/e2e/protocolLogs/03_EthProvider* --exclude="*errors*"

    - name: JSON Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/protocolLogs/03_EthProvider* --include="*errors*"

    - name: JSON Consumer All Logs
      if: always()
      run: grep "" testutil/e2e/protocolLogs/04_jsonConsumer* --exclude="*errors*"

    - name: JSON Consumer Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/protocolLogs/04_jsonConsumer* --include="*errors*"

    - name: Lava Provider All Logs
      if: always()
      run: grep "" testutil/e2e/protocolLogs/05_LavaProvider* --exclude="*errors*"

    - name: Lava Provider Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/protocolLogs/05_LavaProvider* --include="*errors*"

    - name: Lava over Lava All Logs
      if: always()
      run: cat testutil/e2e/protocolLogs/07_lavaOverLava.log

    - name: Lava over Lava Error Only Logs
      if: always()
      continue-on-error: true
      run: cat testutil/e2e/protocolLogs/07_lavaOverLava_errors.log

    - name: RPCConsumer Consumer All Logs
      if: always()
      run: grep "" testutil/e2e/protocolLogs/06_RPCConsumer* --exclude="*errors*"

    - name: RPCConsumer Consumer Error Only Logs
      if: always()
      continue-on-error: true
      run: grep "" testutil/e2e/protocolLogs/06_RPCConsumer* --include="*errors*"
  test-sdk-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.5

      # Setup Paths
      - name: home
        run: pwd && ls -l
      - name: ls usr
        run: ls -l /home/runner/work/lava/lava
      - name: cp lava
        run: cp -r ~/work/lava/lava ~/go/lava
      - name: export PATH
        run: export PATH=$PATH:/go:/go/bin:$(go env GOPATH)/bin:/usr/local:`pwd`:/home/runner/work/lava/lava/
      # - name: export
      #   run: export PATH=$PATH:/go/lava
      - name: export GOPATH
        run: export GOPATH=$GOPATH:$(go env GOPATH):/go:/go/lava:/usr/local:`pwd`
      - name: export LAVA
        run: export LAVA=/home/runner/work/lava/lava
      - name: go env
        run: go env
      - name: pwd
        run: pwd
      - name: tree
        run: tree
      - name: ls -l
        run: ls -l

      # Install Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      # install ts-node
      - name: Install ts-node
        run: npm install -g ts-node

        # Install dependencies and build
      - name: Install dependencies and build
        run: |
          cd ecosystem/lava-sdk
          npm install
          npm run build

      - name: Install telescope dependencies
        run: |
          go mod tidy
          cd ecosystem/lavajs
          npm install
          npm run e2e-setup

      - name: setup test environment
        run: | 
          cd testutil/e2e/sdk/tests
          npm install --save-dev @types/node 

      ######################################################
      ### Run Lava E2E Tests 
      ######################################################
      - name: Run Lava E2E Tests  -timeout 1200s
        run: go test ./testutil/e2e/ -run ^TestLavaSDK -v -timeout 1200s # 20mins

      - name: tail -n 300 Lavad Logs
        if: always()
        run: tail -n 300 testutil/e2e/sdkLogs/00_StartLava.log

      - name: Stake Lava All Logs
        if: always()
        run: cat testutil/e2e/sdkLogs/01_stakeLava.log

      - name: Stake Lava Error Only Logs
        if: always()
        continue-on-error: true
        run: cat testutil/e2e/sdkLogs/01_stakeLava_errors.log

      - name: head -n 300 JSON Proxy Logs
        if: always()
        run: head -n 300 testutil/e2e/sdkLogs/02_jsonProxy.log

      - name: tail -n 300 JSON Proxy Logs
        if: always()
        run: tail -n 300 testutil/e2e/sdkLogs/02_jsonProxy.log

      - name: JSON Proxy Error Only Logs
        if: always()
        continue-on-error: true
        run: cat testutil/e2e/sdkLogs/02_jsonProxy_errors.log

      - name: JSON Provider All Logs
        if: always()
        run: grep "" testutil/e2e/sdkLogs/03_EthProvider* --exclude="*errors*"

      - name: JSON Provider Error Only Logs
        if: always()
        continue-on-error: true
        run: grep "" testutil/e2e/sdkLogs/03_EthProvider* --include="*errors*"

      - name: Lava Provider All Logs
        if: always()
        run: grep "" testutil/e2e/sdkLogs/05_LavaProvider* --exclude="*errors*"

      - name: Lava Provider Error Only Logs
        if: always()
        continue-on-error: true
        run: grep "" testutil/e2e/sdkLogs/05_LavaProvider* --include="*errors*"

      - name: Badge Server All Logs
        if: always()
        run: grep "" testutil/e2e/sdkLogs/01_BadgeServer* --exclude="*errors*"

      - name: Badge Server Error Only Logs
        if: always()
        continue-on-error: true
        run: grep "" testutil/e2e/sdkLogs/01_BadgeServer* --include="*errors*"

      - name: Lava SDK All Logs
        if: always()
        run: grep "" testutil/e2e/sdkLogs/01_sdkTest* --exclude="*errors*"

      - name: Lava SDK Error Only Logs
        if: always()
        continue-on-error: true
        run: grep "" testutil/e2e/sdkLogs/01_sdkTest* --include="*errors*"
